name: sanjayrb
version: 1.0.0+1
publish_to: none
description: My personal portfolio
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  flutter_animate: 4.5.0
  google_fonts: 6.2.1
  url_launcher: 6.3.0
  url_strategy: 0.2.0
  get: 4.6.6
  intl: 0.19.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_native_splash: 2.4.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

