import 'package:sanjayrb/app/constants/timeline_type_constant.dart';
import 'package:sanjayrb/app/data/models/timeline_model.dart';

List<TimelineModel> project = [
  TimelineModel(
    title: "My Personal Portfolio",
    subTitle: "Version : 2.1.0+2",
    date: DateTime(2024, 07, 30),
    type: TimelineTypeConstant.project,
    link: "NA",
    points: [
      '2.1.3+3: Updated content of timeline and fixed minor bugs. 🐞',
      '2.1.0+2: Added new version of Loga Parameshwari Temple app 🎉',
      '2.0.0+2: Revamped the entire app UI and functions for a smoother, more intuitive experience. 🚀',
      '1.0.0+1: An portfolio page for my self to know more about me',
    ],
  ),
  TimelineModel(
    title: "100 Days of Programming",
    subTitle: "Version : 1.4.0+3",
    date: DateTime(2024, 07, 21),
    type: TimelineTypeConstant.project,
    link:
        "https://play.google.com/store/apps/details?id=com.sanjoke.hundred_days_of_programming",
    points: [
      '100 days, 100 unique programs to code in any language of your choice. 🖥️',
      'This app offers both light and dark mode themes. 🌞🌜',
      'Personalized tracking of task completion with submissions via GitHub and LinkedIn posts. 📊',
      'Maintain your streak and stand out. 🌟',
      'By sharing task completions, you can network on LinkedIn and document your progress on GitHub. 🤝📚'
    ],
  ),
  TimelineModel(
    title: "100 Days of Flutter",
    subTitle: "Version : 1.2.7+5",
    date: DateTime(2021, 02, 17),
    type: TimelineTypeConstant.project,
    link:
        "https://play.google.com/store/apps/details?id=com.sanjoke.hundred_days_of_flutter",
    points: [
      'This Application has a complete schedule table for learning all basic widgets in 100 days.',
      'Schedule every unique widget has a day.',
      'Introduction to all the widgets and video references.',
      'Mark as done and filter feature.',
      'Code sample with the output preview.',
      'Full documentation as a website.',
    ],
  ),
  TimelineModel(
    title: "Loga Parameshwari Temple",
    subTitle: "Version : 2.13.15+24",
    date: DateTime(2024, 07, 05),
    type: TimelineTypeConstant.project,
    link:
        "https://play.google.com/store/apps/details?id=com.sanjoke.loga_parameshwari",
    points: [
      '2.13.15+24: Minor update: Resolved image permission issue',
      '2.13.15+24: Minor update: Enhanced Scheduled Pooja navigator',
      '2.13.15+24: Minor update: Improved cloud function for notification text',
      '2.13.15+24: Minor update: Integrated AdMob for mobile advertisements',
      '2.13.12+23: Minor update: Resolved image permission issue',
      '2.13.12+23: Minor update: Enhanced Scheduled Pooja navigator',
      '2.13.12+23: Minor update: Improved cloud function for notification text',
      '2.13.12+23: Minor update: Integrated AdMob for mobile advertisements',
      '2.13.8+22: Security update : Google play policy fix',
      '2.13.8+22: Minor revision : Updated special pooja style',
      '2.13.7+21: Bug fix: Permission issue fixed on storage',
      '2.13.7+21: Minor revision : Updated security update on cloud functions',
      '2.13.7+21: Minor revision : Updated special dates logic, map click',
      '2.13.1+18: Minor revision : Visibility of liked people names',
      '2.13.1+18: Minor revision : User online status',
      '2.13.1+18: Minor revision : History page lazy loading',
      '2.13.1+18: Minor revision : User verification for new pooja addition',
      '2.13.1+18: Minor revision : Permission handler',
      '2.13.1+18: Minor revision : Contact cards',
      '2.13.1+18: Minor revision : Special dates (Amavasay, Pournami & Ailyam Pooja Dates)',
      '2.13.1+18: Minor revision : Android notification channel addition',
      '2.13.1+18: Bug fix: Removed unwanted permissions',
      '2.5.8+16: Minor revision : In App Check in Cloud FireStore',
      '2.5.8+16: Minor revision : Deeplink for pooja page',
      '2.5.4+14: Bug fix: 3d GIF link updated',
      '2.5.4+14: Bug fix: Notification enable',
      '2.5.4+14: Minor revision : Photo swipe features',
      '2.5.4+14: Minor revision : Sponsors name list',
      '2.5.4+14: Minor revision : Payment info page',
      '2.5.4+14: Minor revision : Update date from the UI by the post creator (Edit Page)',
      '2.5.4+14: Minor revision : App Tutorial',
      '2.0.0+10: Added authentication with mobile OTP.',
      '2.0.0+10: Now you can add an image while scheduling the pooja.',
      '2.0.0+10: In-app update checked.',
      '2.0.0+10: New splash screen for preloading information.',
      '2.0.0+10: New profile page for each user.',
      '1.0.0+1: Initial version of the app',
    ],
  ),
];
